version: 0.2

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip"
      - "unzip terraform_0.12.28_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo terraform apply completed on `date`
